# web deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      app: {{ .Release.Name }}-web
  template:
    metadata: 
      labels: 
        app: {{ .Release.Name }}-web
    spec:
      containers: 
        - name: web
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports: 
            - containerPort: {{ .Values.web.service.port }}
          env:
            - name: REDIS_HOST
              value: {{ .Release.Name }}-{{ .Values.redis.service.name }}
            - name: REDIS_PORT
              value: {{ .Values.web.env.REDIS_PORT | quote }}
            
---

# web service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.web.service.name }}
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - protocol: {{ .Values.web.service.protocol }}
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
  type: {{ .Values.web.service.type }}
