services:
  redis:
    image: redis
    container_name: redis-server
    networks:
      - voting-network

  postgres:
    image: postgres
    container_name: postgres-server
    networks:
      - voting-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  web:
    build: 
      context: .
      dockerfile: web/Dockerfile
    container_name: web-server
    ports:
      - "5000:5000"
    networks:
      - voting-network
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis-server
      - POSTGRES_HOST=postgres-server

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker-server
    networks:
      - voting-network
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis-server
      - POSTGRES_HOST=postgres-server

networks:
  voting-network:
    driver: bridge
