services:
  redis:
    image: redis
    container_name: redis-service
    networks:
      - voting-network

  postgres:
    image: postgres
    container_name: postgres-service
    networks:
      - voting-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  web:
    build: 
      context: .
      dockerfile: web/Dockerfile
    image: web-image
    container_name: web-service
    ports:
      - "5000:5000"
    networks:
      - voting-network
    depends_on:
      - redis
      - postgres
    volumes:
      - ./web:/app

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: worker-image
    container_name: worker-service
    networks:
      - voting-network
    depends_on:
      - redis
      - postgres
  
  result:
    build:
      context: .
      dockerfile: result/Dockerfile
    image: result-image
    container_name: result-service
    ports:
      - "5001:5001"
    networks:
      - voting-network
    depends_on:
      - redis
      - postgres
    volumes:
      - ./result:/app

networks:
  voting-network:
    driver: bridge
