apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: result-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-service
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              value: postgres
            - name: PGPORT
              value: "5432"
