apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: web
spec:
  containers:
    - name: web
      image: web-image
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      env:
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
