# Default values for meinan-voting-app.
# This is a YAML-formatted file.

replicaCount: 2

# Web application configuration
web:
  image:
    repository: web-image
    tag: latest
    pullPolicy: Never
  service:
    name: web-service
    type: NodePort
    port: 80 # has to be integer
    targetPort: 5000
    nodePort: 30001
    protocol: TCP
  env:
    REDIS_PORT: "6379" # has to be string

# Worker configuration
worker:
  image:
    repository: worker-image
    tag: latest
    pullPolicy: Never
  env:
    REDIS_PORT: "6379"
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_PORT: "5432"
    DB_NAME: postgres

# Result application configuration
result:
  image:
    repository: result-image
    tag: latest
    pullPolicy: Never
  service:
    name: result-service
    type: NodePort
    port: 80
    targetPort: 5001
    nodePort: 30002
  env:
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_HOST: postgres-service
    DB_PORT: "5432"
    DB_NAME: postgres

# Redis configuration
redis:
  replicas: 1
  image:
    repository: redis
    tag: latest
    pullPolicy: Never
  service:
    name: redis-service
    type: ClusterIP
    protocal: TCP
    port: 6379
    targetPort: 6379

# Postgres configuration
postgres:
  replicas: 1
  image:
    repository: postgres
    tag: latest
    pullPolicy: Never
  service:
    name: postgres-service
    type: ClusterIP
    protocal: TCP
    port: 5432
    targetPort: 5432
  env:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""